INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('AeroFlo ATB Wheels', "",  "",
"", 189, 40, 4);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Clear Shade 85-T Glasses', "", "",
"", 45, 14, 1);
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Cosmic Elite Road Warrior Wheels', "", "",
"", 165, 22, 4);
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
 VALUES ('Cycle-Doc Pro Repair Stand', "", "",
"", 166, 12, 1);
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Dog Ear Aero-Flow Floor Pump', "", "",
"", 5, 25, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Dog Ear Cycle Computer', "", "",
"", 75, 20, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Dog Ear Helmet Mount Mirrors', "", "",
"", 7.45, 12, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
 VALUES ('Dog Ear Monster Grip Gloves', "", "",
"", 15, 30, 1);
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Eagle FS-3 Mountain Bike', "", "",
"", 1800, 8, 2);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Eagle SA-120 Clipless Pedals', "", "",
"", 139.95, 20, 4); 
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Glide-O-Matic Cycling Helmet', "", "",
"", 125, 24, 1); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('GT RTS-2 Mountain Bike', "", "",
"", 1650, 5, 2);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('HP Deluxe Panniers', "", "",
"", 39, 10, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('King Cobra Helmet', "", "",
"", 139, 30, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Kool Breeze Rocket Top Jersey', "", "",
"", 4.99, 40, 4);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Kryptonite Advanced 2000 U-Lock', "", "", 
"", 50, 20, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Nikoma Lok-Tight U-Lock', "", "",
"", 33, 12, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('ProFormance ATB All-Terrain Pedal', "", "",
"", 28, 40, 4);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('ProFormance Toe Klips 2G', "", "",
"", 28, 40, 4);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Pro-Sport Dillo Shades', "", "",
"", 82, 18, 1); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Road Warrior Hitch Pack', "",  "",
"", 175, 6, 5); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Shinoman 105 SC Brakes', "", "",
"", 23.5, 16, 4);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
 VALUES ('Shinoman Deluxe TX-30 Pedal', "", "",
"", 45, 60, 4);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Shinoman Dura-Ace Headset', "", "",
"", 67.5, 20, 4); 
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
 VALUES ('StaDry Cycling Pants', "", "",
"", 69, 22, 3);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
 VALUES ('TransPort Bicycle Rack', "", "",
"", 27, 14, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Trek 9000 Mountain Bike', "", "",
"", 1200, 6, 2); 
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('True Grip Competition Gloves', "", "",
"", 22, 20, 1); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Turbo Twin Tires', "", "",
"", 29, 18, 6);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Ultimate Export 2G Car Rack', "",  "", 
"", 180, 8, 5);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Ultra-2K Competition Tire', "", "",
"", 34, 22, 6);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Ultra-Pro Rain Jacket', "", "",
"", 85, 30, 3); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Victoria Pro All Weather Tires', "", "",
"", 54.95, 20, 4); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Viscount C-500 Wireless Bike Computer', "", "",
"", 49, 30, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Viscount CardioSport Sport Watch', "", "",
"", 179, 12, 1); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Viscount Microshell Helmet', "", "",
"", 36, 20, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Viscount Mountain Bike', "", "",
"", 635, 5, 2);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Viscount Tru-Beat Heart Transmitter', "", "",
"", 47, 20, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Wonder Wool Cycle Socks', "", "",
"", 19, 30, 3);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('X-Pro All Weather Tires', "", "",
"", 24, 20, 6);